### ISSUE TITLE
Cannot compile on Linux Mint 18.2(based on Ubuntu 16.04)

### ISSUE THREAD

**Issue by zarzen** [evilbinary/scheme-lib#18]
Install dependency prompt error:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
freeglut3-dev is already the newest version (2.8.1-2).
freeglut3-dev set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgles1-mesa-dev : Depends: libgles1-mesa (= 12.0.6-0ubuntu0.16.04.1) but 17.2.8-0ubuntu0~16.04.1 is to be installed
```

`make` failed error message:
```
make[2]: Leaving directory '/home/zarzen/Dev/scheme-lib/lib/libnanovg'
make[1]: Circular libalut.so <- libalut.so dependency dropped.
make -C libalut
make[2]: Entering directory '/home/zarzen/Dev/scheme-lib/lib/libalut'
cc -Wall -Wformat -I../libscm -g -DLOG -fPIC  -c -o alut.o alut.c
alut.c:10:21: fatal error: AL/alut.h: No such file or directory
compilation terminated.
Makefile:45: recipe for target 'alut.o' failed
make[2]: *** [alut.o] Error 1
make[2]: Leaving directory '/home/zarzen/Dev/scheme-lib/lib/libalut'
Makefile:71: recipe for target 'libalut.so' failed
make[1]: *** [libalut.so] Error 2
make[1]: Leaving directory '/home/zarzen/Dev/scheme-lib/lib'
Makefile:49: recipe for target 'lib/libscm/libscm.so' failed
make: *** [lib/libscm/libscm.so] Error 2
```

**Comment by evilbinary** [comment]
安装一下这个库，apt-get install   libalut-dev
